### PR TITLE
Change recieved to received

### PR DESCRIPTION
**Pull request by anonrig**
The correct spelling of "recieve" is "receive". More information is at [Cambridge](http://dictionary.cambridge.org/dictionary/english/receive).

### CODE REVIEW

**Comment by mertdogar** [comment]
@anonrig Thank you. Can you please follow the Angular commit message structure? we expect something as follows:
`style(*): Fix typo`

**Comment by anonrig** [comment]
Updated @mertdogar

**Comment by mertdogar** [comment]
@anonrig your branch is out-of-date, can you please rebase it

**Comment by anonrig** [comment]
@mertdogar done.

**Pull request closed without merging**
